name: endpoints_tictactoe
version: 0.0.1
author: Gerwin Sturm
description: A simple Tic Tac Toe game using Google Cloud Endpoints, App Engine, Managed VMs and Dart.
homepage: https://dart-endpoints.appspot.com/
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  appengine: any
  browser: any
  endpoints: any
  googleapis: any
  googleapis_auth: '>=0.2.0'


