name: endpoints_tictactoe
version: 0.0.1
author: Gerwin Sturm
description: A simple Tic Tac Toe game using Google Cloud Endpoints, App Engine, Managed VMs and Dart.
homepage: https://dart-endpoints.appspot.com/
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  appengine: any
  browser: any
  endpoints: any
  google_plus_v1_api: any
  shelf_appengine: any
  tictactoe_v1_api:
    path: dependencies/dart_tictactoe_v1_api_client

dependency_overrides:
  shelf_appengine:
    git:
      url: git@github.com:dart-lang/shelf_appengine.git
      ref: 0-1-dev
  appengine:
    git:
      url: git@github.com:dart-lang/appengine.git
      ref: v0.1
  cloud_datastore:
    git:
      url: git@github.com:dart-lang/cloud_datastore.git
      ref: v0.1
  memcache:
    git:
      url: git@github.com:dart-lang/memcache.git
      ref: v0.1
  endpoints:
    git:
      url: git@github.com:Scarygami/dart_endpoints.git
      ref: master
